# docker-compose.yml

version: '3.8'

services:
  petpoint-py:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app

